### ISSUE TITLE
Tool is crashed when I used Python.Runtime.dll 3.7 version

### ISSUE THREAD

**Issue by SUYOG-KOTKAR** [pythonnet/pythonnet#1174]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6, 3.7
-   Operating System: Windows

### Details

Below are the steps which I performed :

1) Installed python 3.7 on my system.
    Installed pythonnet using "pip install pythonnet" command.
    Python.Runtime.dll generated in site-packages folder.
    Took the backup of whole python 3.7 installation directory.

2) Uninstalled python 3.7.

3) Installed python 3.6 on my system.
    Installed pythonnet using "pip install pythonnet" command.
    Python.Runtime.dll generated in site-packages folder.

4) In my visual studio project, added reference of Python.Runtime.dll from backup python 3.7 installation folder.

5) Added backup python 3.7 installation folder path in Environment Variables.
`
string existing_vars = Environment.GetEnvironmentVariable("Path");
Environment.SetEnvironmentVariable("Path", "C:\\__backup_path_python3.7__\\;" + existing_vars);
`

6) Executed below code:
```
try
{
    if (!PythonEngine.IsInitialized)
    {
        PythonEngine.Initialize();
    }
}
catch (PyScopeException ex)
{

}
```
Tool crashed on "PythonEngine.Initialize()" line.
Tool is not throwing any exception, just crashed.
Please help me to resolve this issue.

**Comment by MechaTechnica** [comment]
Can you give out the inner exception and a full list of your environment variables? I have used 3.7 and 3.6 installing on and off and I have not encountered this problem. I think its reading off the system path instead of the user path you set. See https://superuser.com/questions/867728/user-vs-system-environment-variables-do-system-variables-override-user-variabl
