### ISSUE TITLE
.NET class instances considered Iterable

### ISSUE THREAD

**Issue by danabr** [pythonnet/pythonnet#1234]
### Environment

-   Pythonnet version: 2.5.0
-   Python version: 3.7
-   Operating System: Windows

### Details

All .NET class instances are considered instances of `collections.abc.Iterable`.

```C#

namespace Python.Test {
  public class Empty { }
}
```

```python

def test_not_Iterable():
    """Test regular .NET objects are not iterable"""
    from Python.Test import Empty
    from collections.abc import Iterable

    assert (not isinstance(Empty(), Iterable))
```

The test is expected to pass, but fails:

```
    def test_not_Iterable():
        """Test regular .NET objects are not iterable"""
        from Python.Test import Empty
        from collections.abc import Iterable

>       assert (not isinstance(Empty(), Iterable))
E       AssertionError: assert not True
E        +  where True = isinstance(<Python.Test.Empty object at 0x0000022D3E6DE5C8>, <class 'collections.abc.Iterable'>)
E        +    where <Python.Test.Empty object at 0x0000022D3E6DE5C8> = <class 'Python.Test.Empty'>()
```

**Comment by filmor** [comment]
This is because the `tp_iter` slot is always filled and just throws an error for non-`IEnumerable` types: https://github.com/pythonnet/pythonnet/blob/742463e5804ab2027d5ecf6c6096a2591d77b6f7/src/runtime/classbase.cs#L181-L207

We could do the respective check in the "constructor" of the type here: https://github.com/pythonnet/pythonnet/blob/ec424bb0a8f0217c496898395880cf9b99d073e6/src/runtime/typemanager.cs#L688
