### ISSUE TITLE
make Github web interface work for you

### ISSUE THREAD

**Issue by stonebig** [pythonnet/pythonnet#149]
I would suggest you develop on Master, and keep last release on a side branch. Indeed :
- the github automatic features (like Pulse, Graphs) are rather "master" oriented,
- this would be more one-liners-contributors (via Github Web Interface) friendly,
- visitors would see immediately that the project is still moving,
- as far as i can see, this is the way a majority of other projects are behaving.

As a personnal fact, I lost one hour by proposing my patches first on Master instead of Develop.

**Comment by denfromufa** [comment]
We had a discussion with @tonyroberts and he linked the github guidelines for master and develop branch workflow:

However none of the major python projects follow these guidelines: numpy, ipython, matplotlib, sympy, etc.

Hence I agree with @stonebig on all his points.

So @davidanthoff @brianlloyd @tonyroberts can you please re-consider this confusing workflow for newcomers?

Maybe branches 2.0, 2.1 and master would be much better?

**Comment by davidanthoff** [comment]
I'm no longer involved in this project, I'm afraid...

**Comment by tonyroberts** [comment]
The develop branch was added because there are a large number of functional changes between 2.0 and what has been introduced since. 2.0 was the stable code migrated from subversion, while the develop stuff was more experimental. Now, the develop branch is stable and therefore is (almost) ready to be merged into master. For small incremental bug fixes and changes I have no problem using the master branch, once these major changes from develop have been merged.

Before commenting on a development strategy used by a particular project you need to understand the history of the project.

Moving a PR from one branch to another doesn't take an hour. If it really did take you an hour, then hopefully that hour was well spent in learning how to use git effectively and so not wasted.

I'm closing this for now, as until the 3.5 work is completed in develop and then released (and hence merged into master) I can't see than any further comments on this can be constructive.

**Comment by tonyroberts** [comment]
I've changed the default branch to develop. This will mean that new users see this branch when they go to the github page, and all the graphs will select this branch by default.

**Comment by stonebig** [comment]
hi, I didn't notice that Github allows to change the "default" branch of github. That's 100% answering my issue. Thank you, and sorry not to have proposed it first

**Comment by denfromufa** [comment]
@tonyroberts this is much better with develop as default branch! does master correspond to 2.0? if yes, why it is not named like that? if not, what version does it correspond to on PYPI? thank you for clarifying on the history of the project! is it documented somewhere?
