### ISSUE TITLE
Encoding issue. PythonEngine.RunSimpleString()

### ISSUE THREAD

**Issue by headtrain** [pythonnet/pythonnet#1533]
### Environment

-   Pythonnet version:2.5.2
-   Python version:3.9
-   Operating System:Win10
-   .NET Runtime:6.0 Preview7

### Details

-   According to https://github.com/pythonnet/pythonnet/issues/818

    PythonEngine.Exec("print('你好，世界')");   // is ok
    var test=PythonEngine.Eval("'你好，'+'世界'"); // is ok

but
    PythonEngine.RunSimpleString("print('你好，世界')");
is error:
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

**Comment by lostmsu** [comment]
I just tested this on `master`, and "can't decode" issue is gone.

One can still, however, face `'charmap' codec can't encode characters` error because `sys.stdout.encoding` to which `print` sends the string might not support Unicode. For example, when run from Visual Studio test runner, the `sys.stdout.encoding` on my system is `cp1252`, so a different error appears:

> 'charmap' codec can't encode characters in position 0-4: character maps to <undefined>

The later, however, not a bug in Python.NET.
