### ISSUE TITLE
DLL Import PyScope how to get max performance?

### ISSUE THREAD

**Issue by furkankarayel** [pythonnet/pythonnet#1671]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.7
-   Operating System: windows 
-   .NET Runtime: 3.1

### Details

-   Describe what you were trying to get done.

I want to import DLLs over clr import as fast as possible. Currently the imports take ~13 seconds until my script gets executed. Is there any way to seperate the DLL import process, so I can just execute the script which assumes that the DLLs are already imported. I need to get the best performance as possible. 

My thoughts were that I seperate my current script into clrDependencies and the main part of the script. First of all I execute the clrDependencies file which fills the PyScope with everything I need. Probably there is a way to save the PyScope to have it ready to load again on executing the script. So the long duration import part will be done much faster. Is it possible?

Does anyone have experience with that already? Thanks in advance.

**Comment by filmor** [comment]
This is not a support forum. What you are suggesting will not work since the import time stems from loading (and processing) the actual .NET DLLs. If you have concrete timings on what takes how long, you could look into optimising the load process itself. You can also check whether the current master works better for you, as a lot of the class information is nowadays lazy-loaded.
