### ISSUE TITLE
Dictionary[String,String] object has no attribute 'ToDictionary

### ISSUE THREAD

**Issue by galaplexus** [pythonnet/pythonnet#1743]
### Environment

-   Pythonnet version: 3.0.0-preview2022-02-03
-   Python version: 3.8.10
-   Operating System: Win10
-   .NET Runtime: 6.0

### Details

```C#
using Python.Runtime;
...
        PythonEngine.Initialize();
        using (new PythonAllowThreads())
        {
            using (Py.GIL())
            {
                dynamic block = Py.Import("testfile");
                var dict = new Dictionary<string, string>();
                var o = dict.ToDictionary(kvp=> kvp.Key, kvp => kvp.Value); // that works here
                var b = block.myfn(dict);
                Console.WriteLine($"Done: {b}");
            }
        }
```

```python
def myfn(dict):
    return dict.ToDictionary()
    return dict.ToDictionary(None, None)
    return dict.ToDictionary(None)
    return dict.ToDictionary(lambda kvp: kvp.Key, lambda kvp: kvp.Value)
    return dict.ToDictionary[KeyValuePair[str, str], str, str](lambda kvp: kvp.Key, lambda kvp: kvp.Value)
```

Any type of return will throw the exception: ''Dictionary[String,String]' object has no attribute 'ToDictionary''
Seems weird that it considers the ToDictionary as an attribute and not a method. Even if I specify the types. 

Can someone help? Otherwise I'm gonna need to use this method in C#...

**Comment by filmor** [comment]
The underlying issue is this #55 and requires some implementation effort. `ToDictionary` is not a method of `Dictionary` but an extension defined on `System.Linq.Enumerable` (https://docs.microsoft.com/de-de/dotnet/api/system.linq.enumerable.todictionary?view=net-6.0). You can call it explicitly using `from System.Linq import Enumerable; Enumerable.ToDictionary(...)`.

The error is just a bit misleading, but Python will use attribute access as a last resort when trying to resolve a method, that's why `a.func = lambda: 1; a.func()` works.

**Comment by galaplexus** [comment]
Thanks a lot! I tried to search for the extensions but didn't find this match. Maybe a good idea to document this. What I'm trying to do is not that crazy, and the solution is a bit cryptic.

**Comment by cinnamonrekki** [comment]
@galaplexus could you please post your solution? I have exactly the same issue, but didn't understand from the thread, how to translate dict.ToDictionary(kvp=> kvp.Key, kvp => kvp.Value) to Python.
