### ISSUE TITLE
Unable to Load the .NET dependencies while accessing the methods

### ISSUE THREAD

**Issue by nagamanickamm** [pythonnet/pythonnet#1812]
**### Environment**

-   Pythonnet version: 3.0.0a2 PRE-RELEASE
-   Python version: 3.10.5
-   Operating System: Windows 10
-   .NET Runtime: .Net core 6.0 and 5.0

**### Details**

-   Have created a simple program to 
                 1. Add 2 numbers
                 2. Read XML from File
                 3. Convert Base64 Encode
-    Used PythonNet CLR to import the dll and access all the above methods
      1. **On .NET core 6.0**:
              *  Add 2 numbers worked like charm
              *  Read XML and Covert Base64 threw error 
              *  _System.TypeLoadException: Could not load type 'System.Text.Encoding' from assembly 'System.Text.Encoding, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at DllExport.XMLReader(String filePath)_
       2. **On .NET core 5.0** :
            *  Add 2 numbers worked
            *  Read XML worked
            *  Convert Base64 did not work and threw error
            *  _System.TypeLoadException: Could not load type 'System.Convert' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at ReusableLibariesConsole.Program.Base64_Encode(Byte[] data)_

We have set the .NET version to 2.0 then all 3 errors disappeared however further methods such as Encryption did not work again
System.TypeLoadException: Could not load type 'System.Security.Cryptography.PasswordDeriveBytes' from assembly 'System.Security.Cryptography.Csp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at DllExport.EncryptionManagerClass.Encrypt(String inputData, String password, Int32 bits)

We tried lot of fixes such as setting CPU to x64, changing target framework and nothing worked.
Please let us know if you need further information

**Comment by torch016** [comment]
I also happen to have the same issue but with a different assembly, the error is:

System.TypeLoadException: Could not load type 'System.Data.Dataset' form assembly  'System.Data.Common', Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by torch016** [comment]
After a while I found out that pythonnet does not have a robust code for .NET core. The option that worked for me, was downgrading the .NET version to 4.8

**Comment by filmor** [comment]
@torch016 Seriously, please stop spamming like this on all channels. Just because *you* don't manage to make it run, doesn't mean that it's broken. These `TypeLoadException` errors are clearly from the .NET side of things, and it matters /a lot/ how exactly the project was built and which assembly could not be loaded. It can for example mean that you didn't use a proper `publish` or (as it seems in your case) are not actually using a .NET Core runtime but just do a bare `import clr` for loading. @nagamanickamm Without a reproducible example, this is not actionable. Feel free to comment with a full record of the code you used (.NET and Python) and the compile instructions.
