### ISSUE TITLE
Ability to find pythonnet version at runtime / define __version__

### ISSUE THREAD

**Issue by amueller** [pythonnet/pythonnet#1909]
### Details

-   I would like to be able to find out which version of pythonnet is installed in a particular runtime environment from the python side. Most packages define a `package.__version__` for that purpose. I couldn't find anything like that in pythonnet.

I tried
```python
    print(pythonnet.__version__)
    print([v for v in dir(pythonnet) if "version" in v])
```
I checked on pythonnet==3.0.0rc4.

**Comment by lostmsu** [comment]
As a workaround you could do
```python
from Python.Runtime import PyObject
clr.GetClrType(PyObject).Assembly.GetName().Version
```

**Comment by lostmsu** [comment]
Actually, there's already `clr.__version__`

**Comment by filmor** [comment]
I'd like to adjust the build process to add a version to `pythonnet` directly, instead. To read the `clr` version, you have to have initialised the .NET runtime already.

**Comment by filmor** [comment]
@amueller Is this really necessary nowadays? Since Python 3.8, there is [`importlib.metadata.version`](https://docs.python.org/3.8/library/importlib.metadata.html#version) which will work even when you just do `python setup.py build` in the local checkout. In the end, I would just use this one to define `__version__` as well, just on 3.7 we'd need to fall back to `pkg_resources` which introduces a runtime dependency on `setuptools`.

**Comment by amueller** [comment]
I was actually unaware of that. Thank you, that indeed makes it unnecessary.
