### ISSUE TITLE
PythonNet, strings, encoding

### ISSUE THREAD

**Issue by kuraga** [pythonnet/pythonnet#222]
Good day!

I have a C# (.NET) DLL with method which "takes text encoded in `cp1251`". I want to use it with Python3 + PythonNet (on Windows 10).

But... Python 3 stores strings in unicode, doesn't it? I have a `bytes` variable if I do `text.encode('cp1251')`. And method accepts a string. What I have to do?

Thanks.

**Comment by filmor** [comment]
C# uses UTF-16 strings, so the API that you are using there must be seriously broken to demand something like this. Have you already tried just passing through the string directly instead of trying to encode it? Maybe it just has an outdated documentation.

Otherwise you can try something nasty like:

    "".join(chr(c) for c in text.encode("cp1251"))

**Comment by kuraga** [comment]
Thanks! Think it works, can't check due to other problems...
