### ISSUE TITLE
Unable to install cmdty-storage

### ISSUE THREAD

**Issue by mjburr** [pythonnet/pythonnet#2285]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.12
-   Operating System: Microsoft Windows 10 Pro
-   .NET Runtime:  Microsoft.AspNetCore.App 8.0.0 
Microsoft.NETCore.App 6.0.20
Microsoft.NETCore.App 8.0.0 
Microsoft.WindowsDesktop.App 8.0.0

### Details

-   I am trying to install package cmdty-storage by running pip install cmdty-storage and getting the below error:

Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
ERROR: Could not build wheels for pythonnet, which is required to install pyproject.toml-based projects

**Comment by filmor** [comment]
This problem is not on `pythonnet`. You are using Python 3.12 which is not officially supported by the package you are trying to use, and it has an explicit Python.NET dependency on version 3.0.1. We only support Python 3.12 from 3.0.3 onwards. Either use Python 3.11, explicitly install a newer pythonnet version (that will also have wheels built already), and/or contact the package maintainer to loosen or update their requirement.
