### ISSUE TITLE
coverage

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#237]
Setup coverage for pythonnet. I see 2 problems: how to test both mono and .NET, and how to test interop between .NET and CPython.

**Comment by vmuriart** [comment]
Semi-closed. Still needs coverage from Travis, waiting on SharpCover or MonoCover. Alternatively, OpenCover may work under Core .net

**Comment by vmuriart** [comment]
Coverage was added to `.net` through AppVeyor when running embedded and python tests. There is no mature & maintained coverage for `mono`. For some of the existing tools, they don't conform any existing coverage file format. It's even looking bleak in `core dotnet` since `OpenCover` isn't currently actively working on it.

I think the milestone should be removed on this one or closed as fixed. Thoughts? @denfromufa

**Comment by denfromufa** [comment]
@vmuriart agreed, it least some coverage!

**Comment by vmuriart** [comment]
Readded the milestone so that it counts towards `v2.3.0`. :nerd_face: I had meant to either remove milestone or close issue.
