### ISSUE TITLE
drop python 2.6, 3.2, and 3.3

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#270]
We have Travis CI (Linux and OSX soon) for Python 2.6, but no CI for Python 2.6 on Appveyor (Windows).

Python 2.6 was dropped by major packages (even numpy is dropping support in v1.12.0) and Python 3.6 is going to be added soon.

If anyone is against dropping Python 2.6 let's collect feedback.

**Comment by filmor** [comment]
While we're at it, I guess that Python 3.2 can also be dropped, leading to support for 2.7 and 3.4-6.

**Comment by denfromufa** [comment]
@filmor how about 3.3? according to python docs it should retire in about one year:

https://docs.python.org/devguide/#status-of-python-branches

**Comment by filmor** [comment]
Does that help us? From what I saw until now (which is admittedly not nearly all of the code) we don't use anything in the code that would expect Python >=3.4.

**Comment by vmuriart** [comment]
@denfromufa Python 2.6 is listed on Appveyor's list of [installed software](https://www.appveyor.com/docs/installed-software/#python) but 3.2 isn't.
@filmor I think @denfromufa 's point was that you didn't include py3.3 on your [first comment](https://github.com/pythonnet/pythonnet/issues/270#issuecomment-259070624).

I'm ok with dropping py26, py32, and even py33 since it seems to have less users than py2.6.

https://hynek.me/articles/python3-2016/
http://ianozsvald.com/2016/06/20/results-for-which-version-of-python-2vs3-do-london-data-scientists-use/

We should complete a release for pythonnet now that 3.6 is out, and add a deprecation notice letting users know that we are dropping py2.6, py3.2, py3.3 in the following release.

**Comment by vmuriart** [comment]
According to `setup.py` [classifiers](https://github.com/pythonnet/pythonnet/blob/573f90367137b30519a6b204bed7fafc7b6877ef/setup.py#L340), we don't support py26. @tonyroberts [removed it](https://github.com/pythonnet/pythonnet/commit/8455a42f642df13e6c84b0780fd0448ae1ea8edc) when we added py3.5 for this very reason. In that case we could remove the classifiers for py32, py33 before the next release.

**Comment by filmor** [comment]
I think it's okay for now to just drop 3.2 and 2.6 officially, and for the next release actually rip out code that is just needed for those versions and 3.3.

**Comment by vmuriart** [comment]
I removed the py3.2 tag. If I understood correctly we're removing py3.3 after v2.2.0 release along with the refactoring of dropping all 3 versions.

**Comment by denfromufa** [comment]
reopening to discuss dropping of python 3.3 support

**Comment by denfromufa** [comment]
@dmitriyse i see minimal downloads for python 3.3 builds of pythonnet on anaconda and pypi:

https://anaconda.org/pythonnet/pythonnet/files?sort=ndownloads&sort_order=desc
https://docs.google.com/spreadsheets/d/1gQuad1rYpYEUwa1bzvRVc0wRIhlGNGmusPE_ntEH7jg/edit?usp=sharing

**Comment by dmitriyse** [comment]
@denfromufa  Thank you for the stat. I thing is a quite obvios that we needs to drop 3.3.
Somebody should be assigned to this issue.  I plan to spend my dev efforts to this issue https://github.com/pythonnet/pythonnet/issues/590

**Comment by denfromufa** [comment]
ok, it is safe to drop 3.3 according to this PEP: https://www.python.org/dev/peps/pep-0398/#id21

**Comment by denfromufa** [comment]
closed by #685 and #689
