### ISSUE TITLE
consider using mono provided by Travis CI

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#367]
https://docs.travis-ci.com/user/languages/csharp/#Choosing-runtime-and-version-to-test-against

**Comment by denfromufa** [comment]
Also I tried building with latest Mono and it seems to be stable now:

mono 4.8:

https://github.com/mono/mono/releases

**Comment by vmuriart** [comment]
I tried using their `mono` build environment and it wasn't good, it didn't have the python interpreters (i think it only had 1).

We are using the latest mono too. We unfroze it when we moved the using `travis` containers for testing.

**Comment by denfromufa** [comment]
@vmuriart thanks for checking on this! closing, since we either need to install python or mono :)

**Comment by vmuriart** [comment]
There's also alot of issues w it apparently if your trying to do `core dotnet`. its a user maintained recipe, so no support from travis either.

**Comment by denfromufa** [comment]
also this is not likely to change in the future to have both python and mono:

https://github.com/travis-ci/travis-ci/issues/4090

**Comment by vmuriart** [comment]
Adding a bit more info in case someone wants to revisit. Here's an example of a demo build using `language=csharp` and building with `mono`.

https://travis-ci.org/vmuriart/example-csharp-sharpcover/builds/202442943

Some of the finding from using it. Builds take much longer to start (because they require `sudo` and seems to be limited in resources).

`mono` is not pre-installed, it does something similar to our current setup and download and [installs it with `apt-get`](https://travis-ci.org/vmuriart/example-csharp-sharpcover/builds/202442943#L107)

it does have python 2.7 pre-installed, but trying to use `pip` to install anything [errors out](https://travis-ci.org/vmuriart/example-csharp-sharpcover/builds/202442943#L1044) with
> InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
