### ISSUE TITLE
migrate docs to wiki

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#387]
https://github.com/pythonnet/pythonnet/wiki

http://pythonnet.github.io/

**Comment by vmuriart** [comment]
imho, documentation should be auto-generated from our code and thus version controlled.

I'm not a big fan of wiki's for documentation, but I think it has its usefulness for documenting random tid-bits of info that don't make sense to be part of the code-comments. For example, `project using pythonnet` makes sense as a wiki.

wrt the homepage... yea that is way outdated. I was looking into migrating it to using [Jekyll w/ GitHub pages](https://pages.github.com/). The initial migration of `html` to `md` can be done with http://heckyesmarkdown.com/ or https://domchristie.github.io/to-markdown/. 
I had started doing this earlier, but couldn't decide on a *theme* so I gave up. 

Looks like with Jekyll we can add directives to build the docs. If not, I think @denfromufa mentioned you were looking into `doxygen` and we could try hosting it on https://docs.readthedocs.io/en/latest/

Maybe make this part of `v2.3.0` milestone?

**Comment by denfromufa** [comment]
Doxygen, read the docs, Sphinx, breathe - that combination supports all 3
languages we use - Python, c#, c/c++.

Jekyll is popular, but I don't know Ruby if any coding/installation is
necessary.

**Comment by vmuriart** [comment]
There is some setup required for Jekyll, especially to preview changes w.o pushing upstream. The initial migration (atleast from `html` to `md`) can be done effortlessly and without Jekyll. But setting up the more advanced features of GitHub pages will probably require some Ruby knowledge (which I don't have either).

In order to take the best advantage of `sphynx` (and even help with releases) we should consider migration from `md` to `rst`. I am not a fan of `rst` but its been a pain to make `sphynx` properly work with `md` files since [`recommonmark`](https://github.com/rtfd/recommonmark) isn't quite there yet.

**Comment by denfromufa** [comment]
@vmuriart i'm thinking that maybe our tutorial at least for python should be in jupyter notebooks?
We can then run these notebooks using pytest plugin for jupyter on CI.
There are slight differences when executing in ipython though.
We can then publish notebooks with docker and binder for live interactive notebooks.

**Comment by denfromufa** [comment]
http://mybinder.org

I don't think there is any equivalent for Windows though.

**Comment by vmuriart** [comment]
@denfromufa would it be a separate repo? Can't say I have any experience w them. At this point I'll be glad just having updated static docs 😃 .

**Comment by vmuriart** [comment]
Should the homepage be updated to have minimal boiler plate info and then re-direct to the wiki?
That way we don't have two sets of documentation that may fall out of sync.

**Comment by denfromufa** [comment]
@vmuriart I removed the wiki duplicate, IMO the static webpage should be part of code repo, so that code and docs can be updated in one PR.
