### ISSUE TITLE
home page docs - table of hyperlinked contents removed and broken link

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#425]
http://pythonnet.github.io/

See the header here:
http://pythonnet.sourceforge.net/readme.html

broken link mentioned in the docs:
http://pythonnet.github.io/readme.html

**Comment by vmuriart** [comment]
Did you submit a pr for this?

**Comment by denfromufa** [comment]
Nope

**Comment by vmuriart** [comment]
I think on the header you mean the sidebar right? to restore this we need to change the template we use. One of the default templates has a sidebar, but i didnt like the color scheme/font. 

The link itself can be removed since it was the homepage referencing into the `readme.html` which are now one and the same.

**Comment by filmor** [comment]
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.
