### ISSUE TITLE
Sypport typeof(T) or clr.GetClrType

### ISSUE THREAD

**Issue by vivainio** [pythonnet/pythonnet#432]
In order to do reflection, you need to acquire the Type instance for imported class.

In C#, this is done by

```
Type t = typeof(MyClass)
```

In IronPython, this is done by

```
t = clr.GetClrType(MyClass)
```

Python.net seems to be missing this functionality.

I currently have this horrible hack, and I'm unsure how far it will work:

```python
def get_clr_type(typ):
    """ simulate typeof(T) or GetClrType from IronPython.

    Horrible hack, redo
    """
    name = typ.__module__ + "." + typ.__name__
    return Type.GetType(name)
```

For reference, code using this resides in: https://github.com/vivainio/pynetext/blob/master/pynetext.py

**Comment by denfromufa** [comment]
@vivainio pull requests are welcome!

Your approach is in the right direction:

https://mail.python.org/pipermail/pythondotnet/2005-July/000371.html

**Comment by vivainio** [comment]
@denfromufa Ok, I'll take a look if I can figure it out how to build & work with the codebase :)

**Comment by denfromufa** [comment]
@vivainio pythonnet runs on 2 CI servers: Travis and Appveyor. So the pull request will automatically do this and also run the tests.

You can also look at these docs to see how to build locally:
https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows-and-Linux

Please report any issues back about building locally, so that we can improve the wiki.

**Comment by denfromufa** [comment]
@vivainio thanks for this contribution!

**Comment by KEBO80** [comment]
As an anlternative solution, I came up with the following by creating a static C# helper function:

   public static class ReflectionHelper
    {
        public static Type GetType<T>() => typeof(T);
    }

This I can import this in Python code and use it for any NET type in the folllowing way:

int32type = ReflectionHelper.GetType[System.Int32]()

intt32type is of System.RuntimeType

**Comment by JoaBjo** [comment]
Could you elaborate a little bit on your alternative solution @KEBO80? That class doesn't compile since T is not defined.

**Comment by filmor** [comment]
@JoaBjo Did you try to compile it? :)

This code is valid, the function `GetType<T>()` is a generic function using one type parameter `T` and no function parameters. In C# you would call it as `var int32Type = ReflectionHelper.GetType<System.Int32>()`, KEBO80 gave the corresponding Python syntax (square brackets `[]` instead of `<>` to select the type parameter).

**Comment by JoaBjo** [comment]
Thanks for the reply @filmor. I was confused for a couple of reasons.

1. GetType was not defined as a generic method and hence it didn't compile.
2. The square bracket part was also not there in the python code.

Also for my use case I need the method for a static class. And GetType<T>() doesn't compile for static types in C#. However, for some reason it still works in python when writing GetType[T]() for a static type T. I did not expect that.

Anyways, thanks for clarifying things

**Comment by denfromufa** [comment]
Here is one corner case that was fixed, but needs review:

https://github.com/pythonnet/pythonnet/issues/606

Basically I scanned through all built-in types in `System`.
