### ISSUE TITLE
Install pythonnet 2.3.0 on mac 

### ISSUE THREAD

**Issue by ShekharReddy4** [pythonnet/pythonnet#525]
### Environment

-   Pythonnet version:2.3.0
-   Python version: 2.7.10
-   Operating System: MacOSX Sierra

### Details
Install pythonnet on MacOSX Sierra
-   Describe what you were trying to get done.
Followed this article http://pythonnet.github.io/ to install pythonnet on my mac

-   What commands did you run to trigger this issue? If you can provide a
    `python setup.py build_ext --inplace` trying to run this command

-   The traceback is here 

```python
   /Users/ggku3mac22/Desktop/pyfiles/pythonnet-2.3.0/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
```

**Comment by denfromufa** [comment]
@ShekharReddy4 you need Mono 5.0, pythonnet from master, and some additional instructions:

https://github.com/pythonnet/pythonnet/issues/465#issuecomment-306940183

**Comment by ShekharReddy4** [comment]
@denfromufa  Is that only a possible way, I don't want to install anything apart from just pythonnet. or is there a way that is self-contained.

**Comment by denfromufa** [comment]
@ShekharReddy4 besides pythonnet and dependencies for this build, you will still need Mono on your Mac. Otherwise you can use pythonnet in docker images:

https://hub.docker.com/r/pythonnet/pythonnet/tags/

I'm putting together some notes for OSX here:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX#osx-notes

**Comment by ShekharReddy4** [comment]
@denfromufa  
`besides pythonnet and dependencies for this build, you will still need Mono on your Mac.` Will this be addressed in future releases or will this remain forever.

**Comment by denfromufa** [comment]
@ShekharReddy4 we plan to support OSX builds and testing on Travis CI, but the wheels/conda binaries will likely arrive much later. Currently OSX and Linux require compilation locally due to fast moving Mono target and dependency on Mono C-API. On Windows we do not depend on C-API for .NET.

Why can't you compile pythonnet locally on OSX?

**Comment by denfromufa** [comment]
Mono will always have to be installed on OSX/Linux for pythonnet to work.

**Comment by ShekharReddy4** [comment]
@denfromufa  can you come online on gitter right now?

**Comment by denfromufa** [comment]
I'm closing this issue, since there is no bug report and no feature suggestions that can be supported in pythonnet. For all OSX related issues, let's track them here:

https://github.com/pythonnet/pythonnet/issues/465
