### ISSUE TITLE
Publish OS-specific manylinux1 wheels according to PEP 513 on PYPI

### ISSUE THREAD

**Issue by webknjaz** [pythonnet/pythonnet#616]
### Environment

-   Docker container, but it doesn't really matter

### Actual behavior

Currently, if one wants to `pip install` the package from within linux box, they need to pre-install build dependencies.
Also, `pip` picks sdist (`tar.gz`), which results into having long compilation process during install.

### Expected behavior

I would like `pip` to pick the appropriate wheel and just unpack it.

### Extra

For this to work [PEP513](https://www.python.org/dev/peps/pep-0513/) requires to have `manylinux1` wheels to be built.

It is completely possible to do this (incl. upload to PYPI) via Travis. I can help with this if needed.

P.S. Doing same for macOS is also possible and I suspect that someone would be happy to see it as well :)

**Comment by denfromufa** [comment]
How about Mono dependency? This would require releasing wheels for every
Mono release due to dependence on C-API of Mono. No one checked if
pythonnet binaries are ABI compatible with various Mono versions. But
historically Mono is also not very stable for pythonnet. So pythonnet had
to skip few versions of Mono.
Finally there are some differences in CPython compilation flags on various
Linux flavors. The major one is static vs dynamic linking of libpython.
So can manilinux take care of all of these?

In conda version of this story, biopython just builds mono + pythonnet
together.

**Comment by denfromufa** [comment]
closing in favor of https://github.com/pythonnet/pythonnet/issues/258, please comment with updates in there.
