### ISSUE TITLE
Performance: pythonnet more than 400x slower than identical C#

### ISSUE THREAD

**Issue by mchandschuh** [pythonnet/pythonnet#694]
### Environment

-   Pythonnet version:
```
Michael@BEAST-LP2 MINGW64 /c/src/pythonnet/pythonnet (master)
$ git lol -1
3eb7e58 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #693 from ArvidJB/issue-475
```
-   Python version:
```
Michael@BEAST-LP2 MINGW64 /c/src/pythonnet/pythonnet (master)
$ python --version
Python 3.6.5 :: Anaconda, Inc.
```
-   Operating System:
```
Michael@BEAST-LP2 MINGW64 /c/src/pythonnet/pythonnet (master)
$ systeminfo | grep "OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO N1TET41W (1.15 ), 10/20/2017
```

### Details

-   Describe what you were trying to get done.

    We're trying to greatly improve the performance of the python/C# interop layer. In our use case, we have a user-defined python type that is a sub-class of a C# type. The user-defined python type is invoked repeatedly from within a time loop.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

    This test clearly demonstrates the massive performance difference. I certainly expect loading a python model and invoking it through an interop layer to be slower (perhaps even 2x slower), but we're noticing performance hits way larger than expected. The below test case shows a hit of 400x for simply accessing a property value!

    See source issue https://github.com/QuantConnect/Lean/issues/2026

    On my system the below test produces the following output:
```
// CSharpBenchmark
    Elapsed: 0.7865ms for 100000 iterations. 127145.581691036 KIPS

// PythonBenchmark
    Elapsed: 388.7402ms for 100000 iterations. 257.24121148263 KIPS
```

```csharp
[TestFixture]
public class TestLayeredPerformance
{
    [OneTimeSetUp]
    public void SetUp()
    {
        PythonEngine.Initialize();
    }

    [OneTimeTearDown]
    public void Dispose()
    {
        PythonEngine.Shutdown();
    }

    [Test]
    [TestCase(true, TestName = "CSharpBenchmark")]
    [TestCase(false, TestName = "PythonBenchmark")]
    public void TestPythonInvokingManagedProperty(bool useCSharp)
    {
        IModel model;
        if (useCSharp)
        {
            model = new CSharpModel();
        }
        else
        {
            // create instance of python model
            var pyModel = PythonEngine.ModuleFromString("module", @"
from clr import AddReference
AddReference(""System"")
AddReference(""Python.EmbeddingTest"")

from Python.EmbeddingTest import *

class PythonModel(TestLayeredPerformance.CSharpModel):
    def InvokeModel(self):
        return self.Data
").GetAttr("PythonModel").Invoke();

            model = new ModelPythonWrapper(pyModel);
        }

        // jit
        var data = model.InvokeModel();

        const int iterations = 100000;
        var stopwatch = Stopwatch.StartNew();
        for (int i = 0; i < iterations; i++)
        {
            data = model.InvokeModel();
        }
        stopwatch.Stop();
        var thousandInvocationsPerSecond = iterations / 1000d / stopwatch.Elapsed.TotalSeconds;
        Console.WriteLine($"Elapsed: {stopwatch.Elapsed.TotalMilliseconds}ms for {iterations} iterations. {thousandInvocationsPerSecond} KIPS");
    }

    public interface IModel
    {
        int Data { get; }
        int InvokeModel();
    }

    public class CSharpModel : IModel
    {
        public int Data => 42;
        public virtual int InvokeModel()
        {
            return Data;
        }
    }

    public class ModelPythonWrapper : CSharpModel
    {
        private readonly dynamic impl;

        public ModelPythonWrapper(dynamic impl)
        {
            this.impl = impl;
        }

        public override int InvokeModel()
        {
            using (Py.GIL())
            {
                return impl.InvokeModel();
            }
        }
    }
}
```

-   If there was a crash, please include the traceback here.

   N/A

EDIT: Updated code to use `using (Py.GIL())` and re-ran benchmark tests.

**Comment by mchandschuh** [comment]
@denfromufa - here's a unit test that provides an example of our usage pattern. We have a C# interface which is intended to be implemented in python by deriving from a C# type that already implements the interface. We then define a wrapper to hide the `dynamic` and manage invocation of the GIL.

**Comment by Martin-Molinero** [comment]
- Release windows Py3 performance sampling profiling of the shared unit test. One idea could be to cache the `PyObject Has/GetAttr` result. 

![imagen](https://user-images.githubusercontent.com/18473240/50646684-7456e780-0f55-11e9-8e09-e9e77c691fef.png)


- Another windows Py3 performance sampling profiling use case of Lean, algorithm -> https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/Benchmarks/HistoryRequestBenchmark.py. This profile result is discoureging, since the `Runtime.PyObject_Call()` itself is responsable for half the threads time. We wouldn't be able to cache this call. Any thoughts on how this could be improved (apart from reducing usage)?

![imagen](https://user-images.githubusercontent.com/18473240/50646354-969c3580-0f54-11e9-9c65-232087c50bff.png)

**Comment by ericjohannsen** [comment]
Note than when simply accessing a property value, you are measuring the interop overhead almost directly since the property accessor does almost no work. To discover whether any significant improvement is possible, I suggest creating a simple C/C++ module and measuring the interop overhead on the same machine.

In general, it is advisable to avoid "chatty" interaction between managed and unmanaged code. For more info, see https://stackoverflow.com/a/509719/141172

**Comment by lostmsu** [comment]
This is not a specific issue, but rather a whole area of work on Python.NET

It must be broken apart into specific causes.
