### ISSUE TITLE
Close numpy file in c#

### ISSUE THREAD

**Issue by LaryLary** [pythonnet/pythonnet#738]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: Anaconda 3 5.2.0 (Python 3.6)
-   Operating System: Windows 10

### Details
Well my issue was closed before it was solved so I start a new one... please see: 
https://github.com/pythonnet/pythonnet/issues/736

I am an c#-programmer and want to read a npz-file in my c#-solution and it works great, but when I want to delete the file , I get the exception, that it is still used by an other process. I have tried some things and I have not found a solution.

here is my code:

using ( Py.GIL( ) )
{
   var locking = PythonEngine.AcquireLock( );
   dynamic np = Py.Import("numpy");
   PyObject data = np.load(path);
  
    //do something with the data ....

   data = null;
   np = null;
   PythonEngine.ReleaseLock(locking);
}

with the 3 lines at the end I finally made it possible to read the file again with this code (before this was not possible without closing my app), but it looks it is not enought to close the file.

The answer was that I have to close the file but I dont know how. I tried data.GetAttr("close"); but I get the same error. How can I close data in c#?

Please dont close the issue if it is not solved. I will comment for others what solutions worked!

**Comment by filmor** [comment]
Please don't just open new tickets, you can continue to comment on a closed one if you think there is more to do. This is rude.

But: This is *not* a support forum, the issue tracker is solely for issues with Python.NET itself, which this one is not. The problem you are having is because of lack of knowledge about how Python works. `data.GetAttr("close")` is equivalent to `data.close` in Python, which gives you a *bound method instance*, i.e. a callable object.

You still have to call it: `data.GetAttr("close").Invoke()` should do it.

**Comment by LaryLary** [comment]
All right, thank you very much it worked!
