### ISSUE TITLE
mod_wsgi hangs with import clr

### ISSUE THREAD

**Issue by mikofski** [pythonnet/pythonnet#85]
### Background
* in a flask app using `mod_wsgi` on Apache, if the app has `import clr`, then the application hangs
* possible rehash of [SourceForge Python.NET bug 16](http://sourceforge.net/p/pythonnet/bugs/16/)
>"conflict between django+mod-wsgi and clr?"

**Comment by eisenheimjelid** [comment]
Hi!, exists some solution for this issue? or alternate solution? In my enviroment i have (pip freeze):
Django==1.7.10
django-braces==1.8.1
django-filter==0.11.0
django-mssql==1.7
django-oauth-toolkit==0.9.0
djangorestframework==3.3.1
Markdown==2.6.5
oauthlib==1.0.1
pythonnet==2.0.0
pywin32==219
requests==2.8.1
six==1.10.0
virtualenv==13.1.2

And run with mod_wsgi 4.4.12, python 2.7.11, apache 2.4 on windows server 2012. I think maybe if i use other connector or other web server can function well, because if i remove 'import clr' from my code in Django, Apache+WSGI are well and all function correct, but if i add 'import clr' webserver doesn't anything, logs are empty and server is without errors. And if using django runserver, all function well.

Any idea?

**Comment by mikofski** [comment]
@eisenheimjelid I had to use [IronPython](http://ironpython.net/) with [`subprocess`](https://docs.python.org/2/library/subprocess.html#subprocess.check_output)

    import subprocess
    target = ["~/path/to/IronPython27/ipy.exe", "~/path/to/my_dotnet_app.py", "arg0", ..., "kwargs"]
    retval = subprocess.check_output(target, universal_newlines=True)

a little slow depending on your machine, but works fine.

For Windows you will need [.NET](https://msdn.microsoft.com/en-us/vstudio/aa496123.aspx?f=255&MSPPError=-2147217396) and for Linux/Darwin you will need [Mono](http://www.mono-project.com/)

on [Ubuntu](http://www.ubuntu.com/):

    sudo apt-get install mono-complete

**Comment by eisenheimjelid** [comment]
Thank you @mikofski but that not is my better solution.

Because i use DLL and i require keep open connection with other program on Windows, if i use EXE like function on subprocess (hi.exe args...) imply for each operation send will open and close connection with that program; so will be really slow.

I will search other solution, but 'subprocess' will be my plan b.

So, thanks. Best regards.

PD. The DLL what i use is related with SAP BO, SAP SDK DI API.

**Comment by mikofski** [comment]
related to #180 and #181

**Comment by denfromufa** [comment]
@mikofski @eisenheimjelid why would you use .NET from Flask/Django app?

**Comment by mikofski** [comment]
I needed to use a particular .NET assembly that communicated with an ASP.NET framework to get some data from a MSSQL server. I did not have access to the database directly, nor could I use the ASP.NET framework from Python. It was a black box, and all I was given was the DLL with exposed methods like `GetWeatherDataHeader()` etc. I used subprocess in the interim and we eventually replaced the entire framework with all Django and PostgreSQL on Linux. So no more need for Python.NET on this project. But there are always others.

**Comment by GregoryKimball** [comment]
I found this comment from Graham Dumpleton to solve the problem https://stackoverflow.com/a/4236503

******

Set:

`WSGIApplicationGroup %{GLOBAL}`
See the application issues document on mod_wsgi wiki.

Most likely you have an extension module not designed to work in sub interpreter. The above forces it to run in main interpreter.
