### ISSUE TITLE
How to support python 3.8  windows install ?

### ISSUE THREAD

**Issue by nichenghyx** [pythonnet/pythonnet#983]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: python3.8
-   Operating System: win10

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
python 3.8 win10 
```

**Comment by thedatadoc** [comment]
@filmor - we don't know what @nichenghyx was reporting for sure, but I can confirm there is an issue with installation on Windows 10 Python 3.8.  A SandboxViolation exception is thrown by the setup script.  (The package setup script has attempted to modify files on your system that are not within the EasyInstall build area...)

I don't have time to debug further and determine if the issue is in pythonnet or setuptools right now, but I thought I'd comment here.  I will plan on using 3.7.x for now.

**Comment by filmor** [comment]
There is no official support for Python 3.8 right now. I closed the issue because it was meaningless.
